# all configurations can be found in http://gohugo.io/overview/configuration/
baseurl: "https://hujiaweibujidao.github.io/"
languageCode: "zh-cn"
title: "Hujiawei Bujidao"
paginate: 20
canonifyurls: true
disable404: false
enableEmoji: true
buildDrafts: true
metaDataFormat: "yaml"
defaultLayout: "post"
theme: "casper"
Copyright: "All rights reserved &copy; 2013 - 2017"

# duoshuo short_name but with param name "DisqusShortname"
DisqusShortname: hujiaweibujidao

# hugo special directories. generally do *not* need to modify these
archetypedir: "archetype"
contentdir: "content"
dataDir: "data"
layoutdir: "layouts"
staticdir: "static"
themesdir: "themes"
publishdir: "public"
paginatePath: "page"

# must remain the permalinks used in hexo (or octopress)
permalinks:
  post: /blog/:year/:month/:day/:title/

taxonomies:
  tag: "tags"

# params used in themes
params:
  description: "Happy Coding & Enjoy Living"
  cover: "https://www.bing.com/ImageResolution.aspx?w=1366&h=768"
  #cover: "images/default.jpg"
  author: "hujiawei"
  authorlocation: "Guangdong, China"
  authorwebsite: "https://github.com/hujiaweibujidao"
  bio: "Hujiawei is a mobile developer"
  logo: "images/logo.png"
  githubName: "hujiaweibujidao"
  twitterName: "hujiaweiyinger" #use it as sinaweibo
  #facebookName: "hujiaweiyinger"
  linkedinName: "hujiaweibujidao"
  hideHUGOSupport: false

# menu config. this section defines the area that appears when the user clicks
# the hamburger menu in upper-right hand corner of the site.
menu:
  main:
    - name: "Home"                          # name that appears in the menu list
      weight: -120                          # order it appears more negative == closer to top of list
      identifier: "home"                    # TODO: not sure what this is responsible for
      url: "/"                              # link address to use when user clicks on menu option
    - name: "Android"
      weight: -110
      identifier: "android"
      url: "/android"
    - name: "Python"
      weight: -100
      identifier: "python"
      url: "/python"
    - name: "Swift"
      weight: -90
      identifier: "swift"
      url: "/swift"
    - name: "About"
      weight: -80
      identifier: "about"
      url: "/about"
